pip install robloxpy
pip install Discord
pip install ImageGrab
pip install time
pip install json
pip install requests
pip install os
pip install pypiwin32
pip install Pillow
pip install pycryptodomex
pip install psutil
pip install discordwebhook
